modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "craftingcompass"
version = "${modVersion}"
displayName = "Chris'sCraftingCompass"
authors = "Kristoffer Oltegen Diehl"
description = '''
Recursive crafting-tree planner with JEI integration. Shows what base components you need versus what you have for any recipe.
'''

[[dependencies.craftingcompass]]
modId = "neoforge"
type = "required"
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftingcompass]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftingcompass]]
modId = "jei"
type = "required"
versionRange = "[19.0.0,)"
ordering = "AFTER"
side = "CLIENT"